// <auto-generated />
using System;
using ClipStudio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClipStudio.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260226202740_RenameIgdbColumnsToGameStore")]
    partial class RenameIgdbColumnsToGameStore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("ClipStudio.Core.Entities.Clip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavourite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewStripPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceFolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Unreviewed");

                    b.Property<string>("SuggestedGameName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("IsFavourite");

                    b.HasIndex("SourceFolderId");

                    b.HasIndex("Status");

                    b.ToTable("Clips", (string)null);
                });

            modelBuilder.Entity("ClipStudio.Core.Entities.ClipTag", b =>
                {
                    b.Property<int>("ClipId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClipId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ClipTags", (string)null);
                });

            modelBuilder.Entity("ClipStudio.Core.Entities.ExportJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClipId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteOriginalAfterExport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HighlightId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TrimMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClipId");

                    b.HasIndex("HighlightId");

                    b.HasIndex("Status");

                    b.ToTable("ExportJobs", (string)null);
                });

            modelBuilder.Entity("ClipStudio.Core.Entities.Highlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClipId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("EndTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClipId");

                    b.ToTable("Highlights", (string)null);
                });

            modelBuilder.Entity("ClipStudio.Core.Entities.HighlightTag", b =>
                {
                    b.Property<int>("HighlightId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HighlightId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("HighlightTags", (string)null);
                });

            modelBuilder.Entity("ClipStudio.Core.Entities.Screenshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClipId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("PlaybackTimestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClipId");

                    b.ToTable("Screenshots", (string)null);
                });

            modelBuilder.Entity("ClipStudio.Core.Entities.SourceFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("SourceFolders", (string)null);
                });

            modelBuilder.Entity("ClipStudio.Core.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#607D8B");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameCoverUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("GameStoreAppId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentTagId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("General");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentTagId");

                    b.HasIndex("Type");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("ClipStudio.Core.Entities.TagRelation", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelatedTagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TagId", "RelatedTagId");

                    b.HasIndex("RelatedTagId");

                    b.ToTable("TagRelations", (string)null);
                });

            modelBuilder.Entity("ClipStudio.Core.Entities.Clip", b =>
                {
                    b.HasOne("ClipStudio.Core.Entities.SourceFolder", "SourceFolder")
                        .WithMany("Clips")
                        .HasForeignKey("SourceFolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceFolder");
                });

            modelBuilder.Entity("ClipStudio.Core.Entities.ClipTag", b =>
                {
                    b.HasOne("ClipStudio.Core.Entities.Clip", "Clip")
                        .WithMany("ClipTags")
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClipStudio.Core.Entities.Tag", "Tag")
                        .WithMany("ClipTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clip");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ClipStudio.Core.Entities.ExportJob", b =>
                {
                    b.HasOne("ClipStudio.Core.Entities.Clip", "Clip")
                        .WithMany("ExportJobs")
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClipStudio.Core.Entities.Highlight", "Highlight")
                        .WithMany()
                        .HasForeignKey("HighlightId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Clip");

                    b.Navigation("Highlight");
                });

            modelBuilder.Entity("ClipStudio.Core.Entities.Highlight", b =>
                {
                    b.HasOne("ClipStudio.Core.Entities.Clip", "Clip")
                        .WithMany("Highlights")
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clip");
                });

            modelBuilder.Entity("ClipStudio.Core.Entities.HighlightTag", b =>
                {
                    b.HasOne("ClipStudio.Core.Entities.Highlight", "Highlight")
                        .WithMany("HighlightTags")
                        .HasForeignKey("HighlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClipStudio.Core.Entities.Tag", "Tag")
                        .WithMany("HighlightTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Highlight");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ClipStudio.Core.Entities.Screenshot", b =>
                {
                    b.HasOne("ClipStudio.Core.Entities.Clip", "Clip")
                        .WithMany("Screenshots")
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clip");
                });

            modelBuilder.Entity("ClipStudio.Core.Entities.Tag", b =>
                {
                    b.HasOne("ClipStudio.Core.Entities.Tag", "ParentTag")
                        .WithMany("ChildTags")
                        .HasForeignKey("ParentTagId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentTag");
                });

            modelBuilder.Entity("ClipStudio.Core.Entities.TagRelation", b =>
                {
                    b.HasOne("ClipStudio.Core.Entities.Tag", "RelatedTag")
                        .WithMany()
                        .HasForeignKey("RelatedTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClipStudio.Core.Entities.Tag", "Tag")
                        .WithMany("Relations")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedTag");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ClipStudio.Core.Entities.Clip", b =>
                {
                    b.Navigation("ClipTags");

                    b.Navigation("ExportJobs");

                    b.Navigation("Highlights");

                    b.Navigation("Screenshots");
                });

            modelBuilder.Entity("ClipStudio.Core.Entities.Highlight", b =>
                {
                    b.Navigation("HighlightTags");
                });

            modelBuilder.Entity("ClipStudio.Core.Entities.SourceFolder", b =>
                {
                    b.Navigation("Clips");
                });

            modelBuilder.Entity("ClipStudio.Core.Entities.Tag", b =>
                {
                    b.Navigation("ChildTags");

                    b.Navigation("ClipTags");

                    b.Navigation("HighlightTags");

                    b.Navigation("Relations");
                });
#pragma warning restore 612, 618
        }
    }
}
